### ISSUE TITLE
Added radio button support

### ISSUE THREAD

**Issue by demeureguillaume** [kittee/bootbox#7]
Thanks for the great job.

I needed the support for radio buttons into bootbox.form, so I added it in my fork.
If you want to add it into your repository, the pull request is open (#6).

The code is close of "checkbox" implementation. 

Here an example of radio buttons usage : 
```
...
radioGroup: {
  group: 'radioGroup',
  value: 'value1',
  options: [
    { value: 'value1', text: 'First value' },
    { value: 'value2', text: 'Second value' }
  ],
  type: 'radio'
},
...
```
If you have any question or comment, please feel free to contact me.

Best regards

**Comment by kittee** [comment]
@demeureguillaume thanks for the update!
